apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  tasks:
  - name: simple-task
    taskSpec:
      steps:
      - image: busybox
        args: ['-c', 'sleep 10']
